title: Dance detector
hero_image: images/banner.png
description: Train a computer to help you perfect a dance move!
version: 4
listed: false
copyedit: false
last_tested: "2024-07-02"
steps:
  - title: What you will make
  - title: Video guide
    completion:
    - engaged
  - title: Step-by-step guide
    completion:
    - internal
  - title: What can I do now?
