title: Detetor de dança
hero_image: images/banner.png
description: Treina um computador para ajudar-te a aperfeiçoar um passo de dança!
version: 4
listed: true
copyedit: true
last_tested: "2024-07-02"
steps:
  - 
    title: O que vais fazer
  - 
    title: Cria o teu projeto
    completion:
      - engaged
  - 
    title: Adiciona amostras
  - 
    title: Treina o modelo
    completion:
      - external
