title: Dance detector
hero_image: images/banner.png
description: Train a computer to help you perfect a dance move!
version: 4
listed: false
copyedit: true
last_tested: "2024-07-02"
steps:
  - 
    title: What you will make
  - 
    title: Set up your project
    completion:
      - engaged
  - 
    title: Add samples
  - 
    title: Train the model
    completion:
      - internal
  - 
    title: What can you do now?
    completion:
      - external
