title: Detektor tańca
hero_image: images/banner.png
description: Wytrenuj komputer, aby pomógł Ci udoskonalić Twoje taneczne ruchy!
version: 4
listed: true
copyedit: true
last_tested: "2024-07-02"
steps:
  - 
    title: Co stworzysz
  - 
    title: Skonfiguruj swój projekt
    completion:
      - engaged
  - 
    title: Dodaj próbki
  - 
    title: Wytrenuj model
    completion:
      - internal
  - 
    title: Co możesz teraz zrobić?
    completion:
      - external
