title: Ανιχνευτής χορού
hero_image: images/banner.png
description: Εκπαίδευσε έναν υπολογιστή για να σε βοηθήσει να τελειοποιήσεις μια χορευτική κίνηση!
version: 4
listed: true
copyedit: true
last_tested: "2024-07-02"
steps:
  - 
    title: Τι θα φτιάξεις
  - 
    title: Ρύθμισε το έργο σου
    completion:
      - engaged
  - 
    title: Πρόσθεσε δείγματα
  - 
    title: Εκπαίδευσε το μοντέλο
    completion:
      - εξωτερικός
