title: Dance detector
hero_image: images/banner.png
description: Train a computer to help you perfect a dance move!
version: 4
listed: true
copyedit: true
last_tested: "2024-07-02"
steps:
  - 
    title: Εισαγωγή
  - 
    title: Set up your project
    completion:
      - engaged
  - 
    title: Add samples
  - 
    title: Εκπαιδεύστε το μοντέλο
    completion:
      - internal
  - 
    title: Αναστοχασμός
    completion:
      - internal
