title: Détecteur de danse
hero_image: images/banner.png
description: Entraîne un ordinateur pour t'aider à perfectionner un mouvement de danse !
version: 4
listed: false
copyedit: true
last_tested: "2024-07-02"
steps:
  - 
    title: Ce que tu vas faire
  - 
    title: Configurer ton projet
    completion:
      - engaged
  - 
    title: Ajouter des échantillons
  - 
    title: Entraîner le modèle
    completion:
      - internal
  - 
    title: Que peux-tu faire maintenant ?
    completion:
      - external
